...F.........
======================================================================
FAIL: test_base_pge_w_failing_sas (__main__.BasePgeTestCase)
Test execution of the PgeExecutor class using a RunConfig that defines
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rjb/new_repo_393_old_main/opera-sds-pge/src/opera/test/pge/base/test_base_pge.py", line 174, in test_base_pge_w_failing_sas
    self.assertIn(f"failed with exit code {expected_error_code}", log_contents)
AssertionError: 'failed with exit code 123' not found in '2024-02-26T21:22:55.507437Z, Info, pge_init::logger.py, BasePge, 900001, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:66, "New Log file initialized to pge_20240226T212255.log"\n2024-02-26T21:22:55.507446Z, Info, pge_init::logger.py, BasePge, 900002, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:90, "Loading RunConfig file /home/rjb/new_repo_393_old_main/opera-sds-pge/src/opera/test/pge/base/../../data/test_sas_error_config.yaml"\n2024-02-26T21:22:55.512790Z, Info, pge_init::logger.py, BasePge, 900003, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:105, "Validating RunConfig file /home/rjb/new_repo_393_old_main/opera-sds-pge/src/opera/test/pge/base/../../data/test_sas_error_config.yaml"\n2024-02-26T21:22:55.517427Z, Info, pge_init::logger.py, BasePge, 900005, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:133, "Creating output product directory /home/rjb/new_repo_393_old_main/opera-sds-pge/src/opera/test/pge/base/test_base_pge_1bbj50ectemp/base_pge_test/outputs"\n2024-02-26T21:22:55.517532Z, Info, pge_init::logger.py, BasePge, 900005, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:139, "Creating scratch directory /home/rjb/new_repo_393_old_main/opera-sds-pge/src/opera/test/pge/base/test_base_pge_1bbj50ectemp/base_pge_test/scratch"\n2024-02-26T21:22:55.517582Z, Info, pge_init::logger.py, BasePge, 900006, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:143, "Directory setup complete"\n2024-02-26T21:22:55.517606Z, Info, BASE_PGE::base_pge.py, BasePge, 100004, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:171, "Log file configuration complete"\n2024-02-26T21:22:55.519685Z, Info, BASE_PGE::base_pge.py, BasePge, 100016, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:703, "SAS RunConfig created at base_pge_test/scratch/test_sas_error_config_sas.yaml"\n2024-02-26T21:22:55.519765Z, Debug, BASE_PGE::base_pge.py, BasePge, 101002, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:733, "SAS EXE command line: /usr/bin/bash -c echo; echo sample traceback line1; echo sample traceback line2; exit 123 base_pge_test/scratch/test_sas_error_config_sas.yaml"\n2024-02-26T21:22:55.519772Z, Info, BASE_PGE::base_pge.py, BasePge, 100020, /home/rjb/repos/opera-sds-pge/src/opera/pge/base/base_pge.py:736, "Starting SAS executable"\nsample traceback line1\nsample traceback line2\n/bin/sh: line 0: exit: too many arguments\n2024-02-26T21:22:55.523464Z, Critical, BASE_PGE::base_pge.py, time_and_execute::run_utils.py, 103013, /home/rjb/repos/opera-sds-pge/src/opera/util/run_utils.py:214, "Command "/ u s r / b i n / b a s h   - c   e c h o ;   e c h o   s a m p l e   t r a c e b a c k   l i n e 1 ;   e c h o   s a m p l e   t r a c e b a c k   l i n e 2 ;   e x i t   1 2 3   b a s e _ p g e _ t e s t / s c r a t c h / t e s t _ s a s _ e r r o r _ c o n f i g _ s a s . y a m l" failed with exit code 1"\n2024-02-26T21:22:55.523479Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:597, "overall.log_messages.debug: 1"\n2024-02-26T21:22:55.523486Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:597, "overall.log_messages.info: 9"\n2024-02-26T21:22:55.523492Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:597, "overall.log_messages.warning: 0"\n2024-02-26T21:22:55.523497Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:597, "overall.log_messages.critical: 1"\n2024-02-26T21:22:55.523580Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:602, "overall.os.cpu.seconds.sys: 0.05859299999999999"\n2024-02-26T21:22:55.523589Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:602, "overall.os.cpu.seconds.user: 0.223391"\n2024-02-26T21:22:55.523594Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:602, "overall.os.filesystem.reads: 0"\n2024-02-26T21:22:55.523599Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:602, "overall.os.filesystem.writes: 128"\n2024-02-26T21:22:55.523604Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:602, "overall.os.max_rss_kb.main_process: 35284"\n2024-02-26T21:22:55.523609Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:602, "overall.os.max_rss_kb.largest_child_process: 35284"\n2024-02-26T21:22:55.523614Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:602, "overall.os.peak_vm_kb.main_process: 53896"\n2024-02-26T21:22:55.523621Z, Info, BASE_PGE::base_pge.py, PgeLogger, 100009, /home/rjb/repos/opera-sds-pge/src/opera/util/logger.py:606, "overall.elapsed_seconds: 0.016202774946577847"\n'

----------------------------------------------------------------------
Ran 13 tests in 0.203s

FAILED (failures=1)
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running postprocessor for PostProcessorMixin
Running preprocessor for PreProcessorMixin
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running postprocessor for PostProcessorMixin
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running preprocessor for PreProcessorMixin
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running postprocessor for PostProcessorMixin
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running postprocessor for PostProcessorMixin
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running preprocessor for PreProcessorMixin
Running preprocessor for PreProcessorMixin
Starting SAS execution for PgeExecutor
Running postprocessor for PostProcessorMixin
